export type {
  EmailAlign,
  EmailBlock,
  EmailBlockType,
  EmailColumn,
  EmailDesign,
  EmailDesignStyles,
  EmailSection,
  FooterBlock,
  HeadingBlock,
  HtmlBlock,
  ImageBlock,
  LogoBlock,
  SectionPreset,
  SocialBlock,
  SocialNetwork,
  StarterLayout,
  TextBlock,
} from "@/lib/email/design/types";

export {
  blankDesign,
  createBlock,
  createSection,
  designFromLegacyHtml,
  duplicateBlock,
  duplicateSection,
  EMAIL_COLOUR_SWATCHES,
  ENSIGN_RED,
  extractEmailBody,
  findBlock,
  insertBlock,
  insertSection,
  moveBlock,
  moveBlockBy,
  moveSection,
  newsletterDesign,
  announcementDesign,
  normalizeEmailDesign,
  removeBlock,
  removeSection,
  resolveEmailDesign,
  setSectionPreset,
  starterDesign,
  updateBlock,
  updateSection,
} from "@/lib/email/design/document";

export { compileEmailDesign, safeEmailUrl } from "@/lib/email/design/compile";
export { previewMerge } from "@/lib/email/design/preview";
